_homepage:
    pattern:   /
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: modules , permanent: true }

nte_antiquitas:
    resource: "@NTEAntiquitasBundle/Controller/"
    type:     annotation
    requirements: # new
        _locale: en|fr|de # new
    prefix: /{_locale}/ # new

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

#FOSUserBundle
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password

# fos_user_group:
#     resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#     prefix: /group

#SonataAdminBundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    requirements: # new
        _locale: en|fr|de # new
    prefix: /{_locale}/admin # new

_sonata_admin:
    resource: .
    type: sonata_admin
    requirements: # new
        _locale: en|fr|de # new
    prefix: /{_locale}/admin # new

#SonataUserBundle
soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    requirements: # new
        _locale: en|fr|de # new
    prefix: /{_locale}/admin # new

#SonataMediaBundle
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
