<?php

namespace NTE\AntiquitasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AntiquitasAuteursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AntiquitasAuteursRepository extends EntityRepository
{

    /**
     * {@inheritDoc}
     * 
     * @return array The entities.
     */
    public function findBy(array $criteria, array $orderBy = array('nom' => 'asc', 'prenom' => 'asc'), $limit = null, $offset = null)
    {
        return parent::findBy($criteria, $orderBy, $limit, $offset);
    }
}
